version: '3.8'

services:
  web:
    image: php:8.1-apache
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - MODX_SETUP=yes
    working_dir: /var/www/html
    entrypoint: >
      /bin/bash -c "
      apt update &&
      apt install -y unzip wget libpng-dev libjpeg-dev libonig-dev libxml2-dev zip &&
      docker-php-ext-install mysqli &&
      wget https://modx.com/download/direct?id=revolution -O modx.zip &&
      unzip modx.zip &&
      cp -r modx-*/* . &&
      apache2-foreground
      "

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: modxdb
      MYSQL_USER: modx
      MYSQL_PASSWORD: modxpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

